import { PatientRecord } from '../types';

export const initialPatients: PatientRecord[] = [
  {
    id: 'PAT-2026-001',
    abhaId: '91-4432-8871-9021',
    name: 'Savita Devi',
    age: 42,
    gender: 'Female',
    phone: '+91 98221 44102',
    village: 'Rampur Sub-centre',
    district: 'Solapur, Maharashtra',
    distanceToHospitalKm: 40,
    isPregnant: true,
    gestationWeeks: 34,
    gravidaPara: 'G3 P2 L2',
    vitals: {
      systolicBP: 165,
      diastolicBP: 105,
      pulse: 94,
      spo2: 96,
      bloodSugar: 142,
      temperature: 98.4,
      respiratoryRate: 24,
      hemoglobin: 10.2,
    },
    symptoms: [
      'Chest discomfort & tightness',
      'Breathlessness on exertion',
      'Severe frontal headache',
      'Blurry vision spells',
      'Bilateral pedal edema (swelling)'
    ],
    riskLevel: 'critical',
    triageReason: 'Hypertensive Crisis in 34-Week Pregnancy (Imminent Preeclampsia with Cardiopulmonary symptoms)',
    referral: {
      id: 'REF-MH-2026-8819',
      patientId: 'PAT-2026-001',
      fromFacility: 'Rampur Primary Health Centre (PHC)',
      toFacility: 'Solapur District Civil Hospital (Specialist OBGYN & CCU)',
      referringWorker: 'Sunita Gaikwad (ASHA) / Dr. R. Sharma (MO)',
      assignedSpecialist: 'Dr. Ananya Rao, MD (OBGYN & High-Risk Pregnancy)',
      specialty: 'Obstetrics & Maternal-Fetal Medicine',
      priority: 'Emergency',
      reason: 'Preeclampsia with severe features (BP 165/105, chest pain, vision disturbances) at 34w gestation',
      createdAt: '2026-09-25 10:15 AM',
      currentStatus: 'specialist_review',
      transportMode: '108 Emergency Dial-Ambulance (Unit MH-14-108)',
      ambulanceId: 'MH-14-108',
      estimatedArrivalMinutes: 12,
      prescribedTests: [
        'Urgent Bedside ECG (12-Lead)',
        'Urine Protein / Albumin Dipstick',
        'Serum Creatinine & LFTs',
        'Obstetric Doppler Ultrasound & Biophysical Profile'
      ],
      dischargeInstructions: 'Administered IV Labetalol 20mg bolus. Stabilized BP to 138/88. Continue Oral Labetalol 100mg BD. Strict bed rest. ASHA home BP tracking mandatory every 48 hours.',
      followUpDueDate: '2026-09-27',
      statusHistory: [
        {
          status: 'initiated',
          timestamp: '10:15 AM',
          note: 'Digital Triage flagged Critical High BP & Chest Pain. Emergency Referral generated by ASHA Sunita.'
        },
        {
          status: 'in_transit',
          timestamp: '10:28 AM',
          note: '108 Ambulance Unit MH-14-108 arrived at Rampur PHC. Oxygen initiated; paramedic tele-linked.'
        },
        {
          status: 'arrived_hospital',
          timestamp: '11:18 AM',
          note: 'Arrived at Solapur District Hospital Emergency Triage. E-Referral QR scanned at triage counter.'
        },
        {
          status: 'specialist_review',
          timestamp: '11:30 AM',
          note: 'Assisted Tele-consultation validated by Dr. Ananya Rao. IV antihypertensive administered.'
        }
      ]
    },
    timeline: [
      {
        id: 'EVT-1',
        timestamp: '2026-09-25 09:45 AM',
        stage: 'Village Sub-centre Screening',
        facility: 'Rampur Sub-centre',
        performer: 'ASHA Sunita Gaikwad',
        description: 'Routine 3rd-trimester visit. Patient reported chest tightness and dizziness. Digital BP monitor read 165/105.',
        status: 'completed'
      },
      {
        id: 'EVT-2',
        timestamp: '2026-09-25 10:15 AM',
        stage: 'Digital Triage & SOS Escalation',
        facility: 'MedSetu Rural Engine',
        performer: 'MedSetu AI Triage',
        description: 'Auto-flagged RED: Preeclampsia emergency. 108 Ambulance auto-alerted with patient GPS coordinates.',
        status: 'completed'
      },
      {
        id: 'EVT-3',
        timestamp: '2026-09-25 10:35 AM',
        stage: 'PHC Assisted Teleconsultation',
        facility: 'Rampur PHC Tele-hub',
        performer: 'Dr. R. Sharma & Dr. Ananya Rao',
        description: 'Direct video link established with District Hospital Specialist. Live vitals telemetry streamed.',
        status: 'completed'
      },
      {
        id: 'EVT-4',
        timestamp: '2026-09-25 11:30 AM',
        stage: 'District Hospital Management',
        facility: 'Solapur District Civil Hospital',
        performer: 'Dr. Ananya Rao',
        description: 'Patient admitted to Obstetric HDU. Emergency workup and lab tests conducted.',
        status: 'current'
      },
      {
        id: 'EVT-5',
        timestamp: 'Pending (Within 48h)',
        stage: 'ASHA Closed-Loop Follow-up',
        facility: 'Savita Devi Home, Rampur',
        performer: 'ASHA Sunita Gaikwad',
        description: 'Home BP check, medication compliance, fetal movement check, and mobile reporting to MedSetu.',
        status: 'pending'
      }
    ],
    prescriptions: [
      {
        id: 'RX-101',
        medicationName: 'Tab. Labetalol Hydrochloride',
        dosage: '100 mg',
        frequency: 'Twice daily (BD) with meals',
        duration: '14 days',
        instructions: 'Do not stop abruptly. Regular BP checks every alternate day.'
      },
      {
        id: 'RX-102',
        medicationName: 'Tab. Calcium Carbonate + Vitamin D3',
        dosage: '500 mg',
        frequency: 'Once daily (OD) afternoon',
        duration: '30 days',
        instructions: 'Take 2 hours apart from iron supplements.'
      },
      {
        id: 'RX-103',
        medicationName: 'Tab. Iron Folic Acid (IFA Red)',
        dosage: '100 mg elemental iron',
        frequency: 'Once daily (OD) night',
        duration: '30 days',
        instructions: 'Take with lemon water or plain water; avoid milk or tea.'
      }
    ],
    ambulanceDispatched: true,
    followUpAlertSent: true,
    ashaAssigned: 'Sunita Gaikwad',
    ashaContact: '+91 94220 89123',
    registeredDate: '2026-04-12'
  },
  {
    id: 'PAT-2026-002',
    abhaId: '91-3109-5561-2244',
    name: 'Rameshwar Patil',
    age: 58,
    gender: 'Male',
    phone: '+91 97654 32188',
    village: 'Borgaon',
    district: 'Solapur, Maharashtra',
    distanceToHospitalKm: 32,
    isPregnant: false,
    vitals: {
      systolicBP: 148,
      diastolicBP: 92,
      pulse: 82,
      spo2: 97,
      bloodSugar: 310,
      temperature: 99.1,
      respiratoryRate: 18,
      hemoglobin: 12.4,
    },
    symptoms: [
      'Uncontrolled high blood sugar (>300 mg/dL)',
      'Non-healing ulcer on right foot sole (grade 2)',
      'Numbness and burning sensation in toes',
      'Fatigue and excessive thirst'
    ],
    riskLevel: 'high',
    triageReason: 'Uncontrolled Type 2 Diabetes with Infected Diabetic Foot Ulcer',
    referral: {
      id: 'REF-MH-2026-7731',
      patientId: 'PAT-2026-002',
      fromFacility: 'Borgaon Primary Health Centre',
      toFacility: 'Solapur District Civil Hospital (Diabetic Care Unit)',
      referringWorker: 'ANM Rekha Kadam',
      assignedSpecialist: 'Dr. V. Kulkarni (General Surgeon & Endocrinologist)',
      specialty: 'Endocrinology & Diabetic Foot Care',
      priority: 'Urgent',
      reason: 'Diabetic foot ulcer with local cellulitis; blood sugar 310 mg/dL',
      createdAt: '2026-09-24 02:20 PM',
      currentStatus: 'diagnostics_prescribed',
      transportMode: 'Government Rural Bus / Private Auto',
      prescribedTests: [
        'Pus Culture & Sensitivity',
        'HbA1c Glycated Hemoglobin',
        'Right Foot X-Ray (to rule out osteomyelitis)',
        'Arterial Doppler Lower Limb'
      ],
      dischargeInstructions: 'Surgical wound debridement performed. Regular sterile dressing. Insulin glargine initiation.',
      statusHistory: [
        {
          status: 'initiated',
          timestamp: '02:20 PM (Yesterday)',
          note: 'ANM Rekha logged high blood sugar and ulcer. Referred to District Hospital.'
        },
        {
          status: 'arrived_hospital',
          timestamp: '05:10 PM (Yesterday)',
          note: 'Patient reached hospital via bus. ABHA scanned at registration.'
        },
        {
          status: 'diagnostics_prescribed',
          timestamp: '10:00 AM (Today)',
          note: 'Wound swab taken. X-ray completed.'
        }
      ]
    },
    timeline: [
      {
        id: 'EVT-P1',
        timestamp: '2026-09-24 02:00 PM',
        stage: 'Borgaon Health & Wellness Centre',
        facility: 'Borgaon Health & Wellness Centre',
        performer: 'ANM Rekha Kadam',
        description: 'Patient presented with foot wound not healing for 3 weeks. Glucose 310 mg/dL.',
        status: 'completed'
      },
      {
        id: 'EVT-P2',
        timestamp: '2026-09-24 02:30 PM',
        stage: 'Teleconsultation with Dr. Kulkarni',
        facility: 'Solapur District Civil Hospital',
        performer: 'Dr. V. Kulkarni',
        description: 'Advised immediate hospital referral for surgical debridement and glycemic stabilization.',
        status: 'completed'
      }
    ],
    prescriptions: [
      {
        id: 'RX-201',
        medicationName: 'Inj. Human Mixtard Insulin 30/70',
        dosage: '16 units morning, 10 units night',
        frequency: 'Subcutaneous before meals',
        duration: '30 days',
        instructions: 'Store in cool place or earthen pot with wet cloth.'
      },
      {
        id: 'RX-202',
        medicationName: 'Tab. Amoxicillin + Clavulanic Acid 625mg',
        dosage: '625 mg',
        frequency: 'Twice daily after food',
        duration: '7 days',
        instructions: 'Complete full 7-day course even if wound looks cleaner.'
      }
    ],
    ambulanceDispatched: false,
    followUpAlertSent: true,
    ashaAssigned: 'Kavita Jadhav',
    ashaContact: '+91 98812 34567',
    registeredDate: '2025-11-19'
  }
];
